/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cohorts/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cohort */
        get: operations["cohort_api_v1_cohorts_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ranking-snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_v1_ranking_snapshots__snapshot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Patient */
        post: operations["add_patient_api_v1_patients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Patient */
        get: operations["patient_api_v1_patients__patient_id__get"];
        /** Update Patient */
        put: operations["update_patient_api_v1_patients__patient_id__put"];
        post?: never;
        /** Delete Patient */
        delete: operations["delete_patient_api_v1_patients__patient_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Patient Risks */
        get: operations["patient_risks_api_v1_patients__patient_id__risks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Summary */
        post: operations["summary_api_v1_patients__patient_id__summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comparisons/heart-weight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Comparison */
        post: operations["comparison_api_v1_comparisons_heart_weight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ranking-snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Snapshot */
        post: operations["create_snapshot_api_v1_ranking_snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Workflow */
        patch: operations["workflow_api_v1_patients__patient_id__workflow_patch"];
        trace?: never;
    };
    "/api/v1/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Overrides */
        post: operations["overrides_api_v1_overrides_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset */
        post: operations["reset_api_v1_sessions_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Events */
        get: operations["audit_events_api_v1_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/queue.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_v1_exports_queue_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/voice/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Voice Context */
        post: operations["voice_context_api_v1_voice_context_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/voice/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Voice Session */
        post: operations["voice_session_api_v1_voice_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/voice/tools/{tool_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Voice Tool */
        post: operations["voice_tool_api_v1_voice_tools__tool_name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CohortRead */
        CohortRead: {
            /** Cohort Id */
            cohort_id: string;
            /** Source Hash */
            source_hash: string;
            /** Schema Version */
            schema_version: string;
            /** Accepted Ids */
            accepted_ids: string[];
            /** Accepted Count */
            accepted_count: number;
            /** Source Count */
            source_count: number;
            /** Excluded Count */
            excluded_count: number;
            /** Missing Rows */
            missing_rows: number;
            /** Missing Cells */
            missing_cells: number;
            /** Exclusions */
            exclusions: {
                [key: string]: unknown;
            }[];
            /** Warnings */
            warnings: {
                [key: string]: unknown;
            }[];
            /** Feature Allowlist */
            feature_allowlist: string[];
            /** Source */
            source: string;
            /** License */
            license: string;
            /** Eligible Count */
            eligible_count: number;
            /** Workflow Revision */
            workflow_revision: number;
            /** Current Snapshot Id */
            current_snapshot_id: string | null;
            /** Session Id */
            session_id: string;
            /** Provenance */
            provenance: string;
            /** Sync Mode */
            sync_mode: string;
        };
        /** ComparisonRequest */
        ComparisonRequest: {
            /**
             * Cohort Id
             * @default uci-hf-299-v1
             */
            cohort_id: string;
        };
        /** ContextRequest */
        ContextRequest: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Patient Id */
            patient_id?: string | null;
        };
        /** Evidence */
        Evidence: {
            /** Id */
            id: string;
            /** Field */
            field: string;
            /** Value */
            value: number | boolean;
            /** Unit */
            unit?: string | null;
            /** Predicate */
            predicate: string;
            /** Scale */
            scale: string;
            /** Points */
            points?: number | null;
            /** Contribution */
            contribution?: number | null;
        };
        /** Facts */
        Facts: {
            /** Age */
            age: number;
            /** Anaemia */
            anaemia: boolean;
            /** Creatinine Phosphokinase */
            creatinine_phosphokinase: number;
            /** Diabetes */
            diabetes: boolean;
            /** Ejection Fraction */
            ejection_fraction: number;
            /** High Blood Pressure */
            high_blood_pressure: boolean;
            /** Platelets */
            platelets: number;
            /** Serum Creatinine */
            serum_creatinine: number;
            /** Serum Sodium */
            serum_sodium: number;
            /** Sex */
            sex: boolean;
            /** Smoking */
            smoking: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MethodRead */
        MethodRead: {
            /** Method Id */
            method_id: string;
            /** Label */
            label: string;
            /** Score Kind */
            score_kind: string;
            /** Available */
            available: boolean;
        };
        /** ModelDescriptor */
        ModelDescriptor: {
            /**
             * Family
             * @enum {string}
             */
            family: "logistic_regression" | "random_forest" | "gradient_boosting";
            /** Model Version */
            model_version: string;
            /** Features */
            features: string[];
            /** Classification Threshold */
            classification_threshold: number;
            /** Band Cutoffs */
            band_cutoffs: {
                [key: string]: number;
            };
            /** Explanation Method */
            explanation_method: string;
            /**
             * Calibration Status
             * @constant
             */
            calibration_status: "not_calibrated";
        };
        /** ModelRisks */
        ModelRisks: {
            /** Bundle Id */
            bundle_id: string;
            heart_risk: components["schemas"]["RiskEstimate"];
            kidney_risk: components["schemas"]["RiskEstimate"];
            patient_risk: components["schemas"]["RiskEstimate"];
        };
        /** ModelsRead */
        ModelsRead: {
            /** Methods */
            methods: components["schemas"]["MethodRead"][];
            /** Reports */
            reports: {
                [key: string]: unknown;
            };
            /**
             * Supervised Status
             * @enum {string}
             */
            supervised_status: "ready" | "not_published";
            /** Bundle Id */
            bundle_id: string | null;
            /** Selected Models */
            selected_models: {
                [key: string]: components["schemas"]["ModelDescriptor"];
            };
        };
        /** MutationResult */
        MutationResult: {
            snapshot: components["schemas"]["Snapshot"];
            /** Revision */
            revision: number;
            /** Sync Status */
            sync_status: string;
            /** Replayed */
            replayed: boolean;
        };
        /** OrganIndicator */
        OrganIndicator: {
            /**
             * State
             * @enum {string}
             */
            state: "flagged" | "not_flagged" | "unknown";
            /** Value */
            value: number | null;
            /**
             * Unit
             * @enum {string}
             */
            unit: "%" | "mg/dL";
            /** Label */
            label: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** Organs */
        Organs: {
            heart: components["schemas"]["OrganIndicator"];
            kidney_left: components["schemas"]["OrganIndicator"];
            kidney_right: components["schemas"]["OrganIndicator"];
        };
        /** Override */
        Override: {
            /**
             * Action
             * @enum {string}
             */
            action: "pin" | "defer";
            /** Reason */
            reason: string;
            /** Sequence */
            sequence: number;
            /** Actor */
            actor: string;
        };
        /** OverrideRequest */
        OverrideRequest: {
            /** Command Id */
            command_id: string;
            /** Expected Revision */
            expected_revision: number;
            /** Patient Id */
            patient_id: string;
            /** Session Id */
            session_id: string;
            /**
             * Action
             * @enum {string}
             */
            action: "pin" | "defer" | "reset";
            /** Reason */
            reason: string;
        };
        /** PatientCreateRequest */
        PatientCreateRequest: {
            /** Command Id */
            command_id: string;
            /** Expected Revision */
            expected_revision: number;
            /** Age */
            age: number;
            /** Anaemia */
            anaemia: boolean;
            /** Creatinine Phosphokinase */
            creatinine_phosphokinase: number;
            /** Diabetes */
            diabetes: boolean;
            /** Ejection Fraction */
            ejection_fraction: number;
            /** High Blood Pressure */
            high_blood_pressure: boolean;
            /** Platelets */
            platelets: number;
            /** Serum Creatinine */
            serum_creatinine: number;
            /** Serum Sodium */
            serum_sodium: number;
            /** Sex */
            sex: boolean;
            /** Smoking */
            smoking: boolean;
        };
        /** PatientDeleteRequest */
        PatientDeleteRequest: {
            /** Command Id */
            command_id: string;
            /** Expected Revision */
            expected_revision: number;
            /** Reason */
            reason: string;
        };
        /**
         * PatientMutationRead
         * @description Confirmed receipt: scored add/edit, or deletion without a facts/risk envelope.
         */
        PatientMutationRead: {
            /** Patient Id */
            patient_id: string;
            /** Revision */
            revision: number;
            /** Sync Status */
            sync_status: string;
            facts?: components["schemas"]["Facts"] | null;
            model_risks?: components["schemas"]["ModelRisks"] | null;
        };
        /** PatientRead */
        PatientRead: {
            /** Patient Id */
            patient_id: string;
            /** Cohort Id */
            cohort_id: string;
            /** Ranking Snapshot Id */
            ranking_snapshot_id: string;
            /** Method Id */
            method_id: string;
            /** Model Rank */
            model_rank: number | null;
            /** Call Rank */
            call_rank: number | null;
            /** Priority Band */
            priority_band: string;
            score: components["schemas"]["Score"];
            facts: components["schemas"]["Facts"];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            organs: components["schemas"]["Organs"];
            /** Indicator Policy Version */
            indicator_policy_version: string;
            /** Explanation Method */
            explanation_method: string;
            workflow: components["schemas"]["Workflow"];
            override: components["schemas"]["Override"] | null;
            /** Provenance */
            provenance: string;
            /** Summary Status */
            summary_status: string;
            /** Fact Units */
            fact_units: {
                [key: string]: string;
            };
            /** Evidence Digest */
            evidence_digest: string;
            summary: components["schemas"]["Summary"];
            model_risks?: components["schemas"]["ModelRisks"] | null;
        };
        /** PatientUpdateRequest */
        PatientUpdateRequest: {
            /** Command Id */
            command_id: string;
            /** Expected Revision */
            expected_revision: number;
            /** Age */
            age?: number | null;
            /** Anaemia */
            anaemia?: boolean | null;
            /** Creatinine Phosphokinase */
            creatinine_phosphokinase?: number | null;
            /** Diabetes */
            diabetes?: boolean | null;
            /** Ejection Fraction */
            ejection_fraction?: number | null;
            /** High Blood Pressure */
            high_blood_pressure?: boolean | null;
            /** Platelets */
            platelets?: number | null;
            /** Serum Creatinine */
            serum_creatinine?: number | null;
            /** Serum Sodium */
            serum_sodium?: number | null;
            /** Sex */
            sex?: boolean | null;
            /** Smoking */
            smoking?: boolean | null;
        };
        /** QueueRow */
        QueueRow: {
            /** Patient Id */
            patient_id: string;
            /** Model Rank */
            model_rank: number;
            /** Call Rank */
            call_rank: number;
            /** In Queue */
            in_queue: boolean;
            /** Priority Band */
            priority_band: string;
            score: components["schemas"]["Score"];
            facts: components["schemas"]["Facts"];
            /** Reason */
            reason: string;
            /** Workflow State */
            workflow_state: string;
            override: components["schemas"]["Override"] | null;
            model_risks?: components["schemas"]["ModelRisks"] | null;
        };
        /** ResetRequest */
        ResetRequest: {
            /** Command Id */
            command_id: string;
            /** Expected Revision */
            expected_revision: number;
            /** Reason */
            reason: string;
        };
        /** RiskEstimate */
        RiskEstimate: {
            /** Score */
            score: number;
            /**
             * Band
             * @enum {string}
             */
            band: "lower" | "middle" | "higher";
            /** Classification Positive */
            classification_positive: boolean;
            /** Classification Threshold */
            classification_threshold: number;
            /**
             * Model Family
             * @enum {string}
             */
            model_family: "logistic_regression" | "random_forest" | "gradient_boosting";
            /** Model Version */
            model_version: string;
            /**
             * Score Kind
             * @default model_output
             * @constant
             */
            score_kind: "model_output";
            /**
             * Calibration Status
             * @default not_calibrated
             * @constant
             */
            calibration_status: "not_calibrated";
            /**
             * Prediction Provenance
             * @enum {string}
             */
            prediction_provenance: "development_in_sample" | "held_out_test" | "new_patient_inference";
            /**
             * Explanation Method
             * @enum {string}
             */
            explanation_method: "linear_log_odds" | "recorded_features_no_local_attribution";
            /** Evidence */
            evidence: components["schemas"]["RiskEvidence"][];
            /** Intercept */
            intercept?: number | null;
        };
        /** RiskEvidence */
        RiskEvidence: {
            /** Id */
            id: string;
            /** Field */
            field: string;
            /** Value */
            value: number | boolean;
            /** Unit */
            unit?: string | null;
            /** Predicate */
            predicate: string;
            /**
             * Scale
             * @enum {string}
             */
            scale: "log_odds" | "recorded_measurement";
            /** Contribution */
            contribution?: number | null;
        };
        /** Score */
        Score: {
            /** Value */
            value: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "points" | "model_output" | "calibrated_probability";
            /** Label */
            label: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Explanation Method */
            explanation_method: string;
            /** Version */
            version: string;
            /** Prediction Provenance */
            prediction_provenance?: string | null;
            /** Intercept */
            intercept?: number | null;
            /** Calibration Status */
            calibration_status?: string | null;
        };
        /** Snapshot */
        Snapshot: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Cohort Id */
            cohort_id: string;
            /** Source Hash */
            source_hash: string;
            /** Created At */
            created_at: string;
            /** Session Id */
            session_id: string;
            /** Workflow Revision */
            workflow_revision: number;
            /** Method Id */
            method_id: string;
            /** Capacity */
            capacity: number;
            /** Mode */
            mode: string;
            /** Eligible Count */
            eligible_count: number;
            /** Selected Count */
            selected_count: number;
            /** Tie Policy */
            tie_policy: string;
            /** Rows */
            rows: components["schemas"]["QueueRow"][];
            /** Queue */
            queue: components["schemas"]["QueueRow"][];
            /** Workflow */
            workflow: {
                [key: string]: string;
            };
            /** Overrides */
            overrides: {
                [key: string]: components["schemas"]["Override"];
            };
            /** Provenance */
            provenance: string;
            /** Sync Mode */
            sync_mode: string;
            /** Model Bundle Id */
            model_bundle_id?: string | null;
        };
        /** SnapshotRequest */
        SnapshotRequest: {
            /** Command Id */
            command_id: string;
            /** Expected Revision */
            expected_revision: number;
            /**
             * Cohort Id
             * @default uci-hf-299-v1
             */
            cohort_id: string;
            /**
             * Method Id
             * @default points_v1
             */
            method_id: string;
            /**
             * Capacity
             * @default 25
             */
            capacity: number;
            /**
             * Mode
             * @default operational
             * @enum {string}
             */
            mode: "operational" | "benchmark";
        };
        /** Summary */
        Summary: {
            /** Patient Id */
            patient_id: string;
            /** Evidence Digest */
            evidence_digest: string;
            /** Text */
            text: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Limitations */
            limitations: string[];
            /** Status */
            status: string;
            /** Prompt Version */
            prompt_version: string;
            /** Generator Version */
            generator_version: string;
        };
        /** SummaryRequest */
        SummaryRequest: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Evidence Digest */
            evidence_digest: string;
        };
        /** ToolRequest */
        ToolRequest: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Patient Id */
            patient_id?: string | null;
            /**
             * Limit
             * @default 3
             */
            limit: number;
            /**
             * Report Id
             * @default case-benchmark-v1
             */
            report_id: string;
            /**
             * Cohort Id
             * @default uci-hf-299-v1
             */
            cohort_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VoiceContextRead */
        VoiceContextRead: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Patient Id */
            patient_id: string | null;
            /** Cohort Id */
            cohort_id: string;
            /** Method Id */
            method_id: string;
            /** Tool Token */
            tool_token: string;
            /** Expires At */
            expires_at: number;
            /** Max Duration Seconds */
            max_duration_seconds: number;
        };
        /** VoiceSessionRead */
        VoiceSessionRead: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Patient Id */
            patient_id: string | null;
            /** Cohort Id */
            cohort_id: string;
            /** Method Id */
            method_id: string;
            /** Tool Token */
            tool_token: string;
            /** Expires At */
            expires_at: number;
            /** Max Duration Seconds */
            max_duration_seconds: number;
            /** Signed Url */
            signed_url: string;
            /**
             * Connection Type
             * @default websocket
             * @constant
             */
            connection_type: "websocket";
            /** Text Only */
            text_only: boolean;
        };
        /** VoiceSessionRequest */
        VoiceSessionRequest: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Patient Id */
            patient_id?: string | null;
            /**
             * Text Only
             * @default false
             */
            text_only: boolean;
        };
        /** Workflow */
        Workflow: {
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "reviewed" | "contacted" | "needs_clinician_review";
            /** Revision */
            revision: number;
        };
        /** WorkflowRequest */
        WorkflowRequest: {
            /** Command Id */
            command_id: string;
            /** Expected Revision */
            expected_revision: number;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "reviewed" | "contacted" | "needs_clinician_review";
            /** Reason */
            reason?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    cohort_api_v1_cohorts_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CohortRead"];
                };
            };
        };
    };
    models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsRead"];
                };
            };
        };
    };
    snapshot_api_v1_ranking_snapshots__snapshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_patient_api_v1_patients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientMutationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patient_api_v1_patients__patient_id__get: {
        parameters: {
            query: {
                snapshot_id: string;
            };
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_patient_api_v1_patients__patient_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientMutationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_patient_api_v1_patients__patient_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientMutationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patient_risks_api_v1_patients__patient_id__risks_get: {
        parameters: {
            query: {
                snapshot_id: string;
            };
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRisks"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_v1_patients__patient_id__summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummaryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    comparison_api_v1_comparisons_heart_weight_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_snapshot_api_v1_ranking_snapshots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workflow_api_v1_patients__patient_id__workflow_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overrides_api_v1_overrides_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_api_v1_sessions_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_events_api_v1_audit_events_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_v1_exports_queue_csv_get: {
        parameters: {
            query: {
                snapshot_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voice_context_api_v1_voice_context_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceContextRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voice_session_api_v1_voice_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voice_tool_api_v1_voice_tools__tool_name__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
